name: CI

on:
  push:
    branches: [ trunk ]
  pull_request:
    branches: [ trunk ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Build
      run: |
        go build ./cmd

    - name: Run Tests
      run: |
        go test -v ./cmd/... -coverprofile=coverage.txt -covermode=atomic

    - name: Run Go Analysis
      run: |
        go vet ./cmd/...
        go list -e ./cmd/... 2>&1 | grep -v '^$'
        go fmt ./cmd/...
        go mod tidy

    - name: Show Coverage
      run: |
        go tool cover -func=coverage.txt
